default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: task1_development
  username: task1
  password: task

test:
  <<: *default
  database: task1_test
  username: task1
  password: task

production:
  <<: *default
  database: task1_production
  username: task1
  password: <%= ENV["AGUIARSSESSORIA_DATABASE_PASSWORD"] %>
